<header id="headerinc" >


<div id = "top">
 <div class = "logo">
 <a href="index.html">
<img src="images/logo.jpg" alt = "companylogo">
</a>
 </div>
</div>
 

<div id = "header">
<h1>Zomato</h1>
</div>


<div id="first">
<div class="Menu">
        	<nav>                                                                         
        		<a href="index.php">Home</a>
                <a href="jobs.php">Jobs</a>
				<a href="apply.php">Apply</a>
				<a href="about.php">About</a>
				<a href="manage.php">Manage</a>
				<a href="phpenhancements.php">PHP Enhancements</a>
		  	</nav>
</div>
</div>
</header>